# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc2d300ad41b12407b0abda060a9f1d655db804d6080b2b535d82afcab2b0049267192daab0d0fda631c7fa981036fc6464c984840b2d31a0c9a65dc4553542d

test:
  secret_key_base: a80d66bacf468f7010b6856f1759afd7c4f3ee360a86d4e71b882acd6f151483e3cc05fa0a6a40e7177bd60571463a6589d51e984f03dcb8a12bd093a1aea076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
